### ISSUE TITLE
pdf2img, Error: Command failed: identify -format %n /docfire/EON.pdf 

### ISSUE THREAD

**Issue by SPlatten** [fitraditya/node-pdf2img#22]
I've just installed pdf2img on my iMAC:

Running: macOS Sierra version 10.12.4
Node version 7.8.0

I'm trying to write a robust PDF to text package, I first use pdf2json to parse the file, if it contains no text nodes with content I then try the following:

        pdf2img   = require("pdf2img")
        var strFile = __dirname + "/" + aryOptions[0];
        console.log(strFile);
        pdf2img.setOptions({type:"png"
					   ,size:8192
					,density:600
				  ,outputdir:__dirname + "/output"
				 ,targetname:"pdf"});
        pdf2img.convert(strFile, function(err, info) {
		if ( err ) {
			console.log(err);
		} else {
			console.log(info);
		}
        });

Unfortunately this fails with:

        /bin/sh: identify: command not found
        child_process.js:524
        throw err;
        ^
        
        Error: Command failed: identify -format %n /docfire/EON.pdf
        /bin/sh: identify: command not found
        
        at checkExecSyncError (child_process.js:481:13)
        at execSync (child_process.js:521:13)
        at async.waterfall.pages (/docfire/node_modules/pdf2img/lib/pdf2img.js:47:32)
        at fn (/docfire/node_modules/async/lib/async.js:638:34)
        at Immediate.<anonymous> (/docfire/node_modules/async/lib/async.js:554:34)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)

[Edit] I have made some progress...after installing the dependencies which I missed initially, the output is now:

        execvp failed, errno = 2 (No such file or directory)
        gm identify: "gs" "-q" "-dBATCH" "-dSAFER" "-dMaxBitmap=50000000" "-dNOPAUSE" "-sDEVICE=ppmraw" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4" "-r72x72" "-sOutputFile=/var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/gmretZGf" "--" "/var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/gmdtH8SW" "-c" "quit".
        gm identify: Postscript delegate failed (/docfire/EON.pdf).
        gm identify: Request did not return an image.
        child_process.js:524
            throw err;
            ^
        Error: Command failed: gm identify -format %n /docfire/EON.pdf
        execvp failed, errno = 2 (No such file or directory)
        gm identify: "gs" "-q" "-dBATCH" "-dSAFER" "-dMaxBitmap=50000000" "-dNOPAUSE" "-sDEVICE=ppmraw" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4" "-r72x72" "-sOutputFile=/var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/gmretZGf" "--" "/var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/gmdtH8SW" "-c" "quit".
        gm identify: Postscript delegate failed (/docfire/EON.pdf).
        gm identify: Request did not return an image.
        
        at checkExecSyncError (child_process.js:481:13)
        at execSync (child_process.js:521:13)
        at async.waterfall.pages (/docfire/node_modules/pdf2img/lib/pdf2img.js:47:32)
        at fn (/docfire/node_modules/async/lib/async.js:638:34)
        at Immediate.<anonymous> (/docfire/node_modules/async/lib/async.js:554:34)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)

I've checked both the path and the file name, both are correct and exist.

After searching around I found that I had to also install:

        brew install ghostscript

All works now.

**Comment by AlexanderKozhevin** [comment]
@SPlatten I installed packages, but it keeps giving me the same error.
