### ISSUE TITLE
Is anyone still working on this?

### ISSUE THREAD

**Issue by SPlatten** [fitraditya/node-pdf2img#23]
There seem to be a whole bunch of people experiencing the same problem, in that PDF's will not be converted to images.

I have a bunch of 0 byte png files and the error:
        /docfire/node_modules/gm/lib/command.js:228
        proc.stdin.once('error', cb);
        ^
        
        TypeError: Cannot read property 'once' of undefined
            at gm._spawn (/docfire/node_modules/gm/lib/command.js:228:15)
            at /docfire/node_modules/gm/lib/command.js:140:19
            at series (/docfire/node_modules/array-series/index.js:11:36)
            at gm._preprocess (/docfire/node_modules/gm/lib/command.js:177:5)
            at gm.stream (/docfire/node_modules/gm/lib/command.js:138:10)
            at convertPdf2Img (/docfire/node_modules/pdf2img/lib/pdf2img.js:92:6)
            at /docfire/node_modules/pdf2img/lib/pdf2img.js:67:9
            at /docfire/node_modules/async/lib/async.js:246:17
            at /docfire/node_modules/async/lib/async.js:122:13
            at _each (/docfire/node_modules/async/lib/async.js:46:13)

I've modified command.js inserting:
        if ( !(typeof proc == "object"
        && typeof proc.stdin == "object"
        && typeof proc.stdin.once == "function") ) {
        	return cb(new Error("imageMagick, WTF is going on?"));
	}

Just before:
        proc.stdin.once('error', cb); 

Now the error and exception is:
        events.js:163
              throw er; // Unhandled 'error' event
              ^
        
        Error: imageMagick, WTF is going on?
            at gm._spawn (/docfire/node_modules/gm/lib/command.js:231:13)
            at /docfire/node_modules/gm/lib/command.js:140:19
            at series (/docfire/node_modules/array-series/index.js:11:36)
            at gm._preprocess (/docfire/node_modules/gm/lib/command.js:177:5)
            at gm.stream (/docfire/node_modules/gm/lib/command.js:138:10)
            at convertPdf2Img (/docfire/node_modules/pdf2img/lib/pdf2img.js:92:6)
            at /docfire/node_modules/pdf2img/lib/pdf2img.js:67:9
            at /docfire/node_modules/async/lib/async.js:246:17
            at /docfire/node_modules/async/lib/async.js:122:13
            at _each (/docfire/node_modules/async/lib/async.js:46:13)

**Comment by fitraditya** [comment]
Hi there,

I made some updates to fix some issues.
This module requires ImageMagick (identify) and GraphicsMagick.
