### ISSUE TITLE
Bad argument error

### ISSUE THREAD

**Issue by antoniobrandao** [fitraditya/node-pdf2img#8]
Node: v5.10.0
System: Yosemite
pdf2img: 0.1.2

code:

```
var target_path = path.resolve(__dirname, '../', '../', '../', 'builds/', 'development/', 'upload/', 'images/');
var input = req.files.file.path;

console.log('input: ' + input);
console.log('target_path: ' + target_path);

pdf2img.setOptions({
    type: 'png',                      // png or jpeg, default png 
    size: 1024,                       // default 1024 
    density: 600,                     // default 600 
    outputdir: target_path
});

pdf2img.convert(input, function(info) {
    console.log(info);
});
```

Error:

```
Uncaught Exception:
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:343:9)
    at PDF.exec (/app/node_modules/pdfinfo/lib/pdfinfo.js:62:17)
    at async.waterfall.pages (/app/node_modules/pdf2img/lib/pdf2img.js:43:18)
    at fn (/app/node_modules/pdf2img/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/app/node_modules/pdf2img/node_modules/async/lib/async.js:554:34)
```

Logs:

```
input: /app/builds/development/upload/images/e874b364713af5f7f7f1bc8e8a924fcb.pdf
target_path: /app/builds/development/upload/images
```

**Comment by fitraditya** [comment]
Seems like you don't have xpdf installed.
Pdfinfo required xpdf. Try to install it first.

PS: I plan to remove pdfinfo in the next release.

**Comment by fitraditya** [comment]
I removed pdfinfo as dependency. Now this module only requires GraphicsMagick.
